name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
          
  deploy:
    name: Deploy FastAPI App
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy FastAPI with Nginx
        run: |
          echo "Deploying FastAPI..."
          # Pull latest changes
          git pull origin main
          
          # Restart FastAPI service (Modify based on your server setup)
          sudo systemctl restart fastapi

          # Restart Nginx to apply new changes
          sudo systemctl restart nginx
